name: deploy

on:
  push:
    branches: ["main"]

jobs:
  generate_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies 📦
        run: bun install

      - name: Generate 💚
        run: bun generate

      - name: Github Pages Deploy 🏳️
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public